# Generated by Django 2.2.7 on 2020-11-13 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pet',
            new_name='Usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='name',
            new_name='nombre',
        ),
    ]
